# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install MFC components
      run: |
        # 使用 Visual Studio Installer 安装 MFC 组件
        $installerPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
        $installPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
        
        # 安装 MFC 组件
        & "$installerPath" --modify --installPath "$installPath" `
          --add Microsoft.VisualStudio.Component.VC.ATLMFC `
          --add Microsoft.VisualStudio.Component.VC.MFC.ARM64 `
          --add Microsoft.VisualStudio.Component.VC.MFC.ARM `
          --add Microsoft.VisualStudio.Component.VC.MFC.x86.x64 `
          --quiet --norestart --wait
 
    - name: Build MFC Application
      run: |
        msbuild 名字已消失了认识的人的评价.sln /p:Configuration=Debug /p:Platform="x86"
      shell: cmd
